_wandb:
    value:
        cli_version: 0.21.0
        e:
            15apfl3x9veaeu4twqo5pix4cfemzfx9:
                args:
                    - locate-map
                    - --device
                    - "5"
                    - SPIDER_example.json
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "214643507200"
                        used: "108055277568"
                executable: /home/zross/src/miniconda3/envs/torch/bin/python
                git:
                    commit: cd29c5f980d64aab732406d1612f8515cf1ab10d
                    remote: https://github.com/interseismic/SPIDER.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c4baf694-212a-51d1-dda4-6aaabf1e249c
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-8134776e-21e6-55fb-4bd8-227b0b15e1aa
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c7757c02-7fab-bf50-4884-8b1f70691c49
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-ce321b5d-b3b9-f7a0-1707-a34a2b05cab1
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-0153dabd-2bfa-cb8a-b23d-d1c504c841c8
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-7bbda6ef-773f-2b5d-1617-1ec78edc8a40
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-e480cdd4-9e08-0b30-15bb-a2e23ef34e11
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-5f9e96c7-e25f-7a7a-4df8-caf6f713937d
                host: ghisallo.gps.caltech.edu
                memory:
                    total: "1622359396352"
                os: Linux-5.14.0-570.51.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: -m spider.cli
                python: CPython 3.13.5
                root: /home/zross/git/SPIDER/example
                startedAt: "2026-02-18T01:19:02.746188Z"
                writerId: 15apfl3x9veaeu4twqo5pix4cfemzfx9
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size_sgld:
    value: 1000000
batch_size_warmup:
    value: 1000000
checkpoint_interval:
    value: 100
devices:
    value:
        - 5
dt_lr_mult:
    value: 0.2
lr_sampler:
    value: 0.01
lr_warmup:
    value: 0.001
phase_unc:
    value:
        - 0.02
        - 0.03
phase1_epochs:
    value: 1000
phase2_epochs:
    value: 100
phase3_epochs:
    value: 100
phase4_epochs:
    value: 100000
sample_write_interval:
    value: 100
sampler_backend:
    value: psgld
sampler_lr_mode:
    value: per_obs
sampler_preconditioner:
    value: rmsprop
sampler_preconditioning:
    value: true
sampler_temperature:
    value: 1
save_every_n:
    value: 10
total_dtimes:
    value: 39295
total_events:
    value: 749
